# Uncomment the following to deploy this app as a static site on render
- type: web
  name: nextjs-static
  env: static
  buildCommand: yarn; yarn build; yarn next export
  staticPublishPath: dist
  pullRequestPreviewsEnabled: true     # optional
  envVars:
  - key: NODE_ENV
    value: production